<?php
#
# DO NOT EDIT THIS FILE
# ---------------------
# The Semiologic theme features a custom.php feature. This allows to hook into
# the template without editing its php files. That way, you won't need to worry
# about losing your changes when you upgrade your site.
#
# You'll find detailed sample files in the custom-samples folder
#


/*
RawSugar guided search template
*/

# show header
include_once TEMPLATEPATH . '/header.php';

do_action('before_the_entries');
do_action('before_the_entry');
?>
<div id="content" class="narrowcolumn">

<?php rs_search_results(); ?>
</div>

<?php
do_action('after_the_entry');
do_action('after_the_entries');

# show footer
include_once TEMPLATEPATH . '/footer.php';
?>