<?php
#
# DO NOT EDIT THIS FILE
# ---------------------
# The Semiologic theme features a custom.php feature. This allows to hook into
# the template without editing its php files. That way, you won't need to worry
# about losing your changes when you upgrade your site.
#
# You'll find detailed sample files in the custom-samples folder
#
?>
<div id="ext_sidebar" class="sidebar">
<div class="pad">
<ul>
<?php
if ( function_exists('dynamic_sidebar') )
{
	#echo '<li style="background-color: yellow;">';
	#var_dump($default_layout, $active_layout);
	#echo '<li>';

	dynamic_sidebar($sidebar_id);
}
else  # no widgets
{


if ( get_nav_menu('sidebar_nav') ) :
?>	<li>
		<div class="widget display_sidebar_nav_widget">
		<h2>Navigation</h2>
		<?php display_nav_menu('sidebar_nav'); ?>		</div>
	</li>
<?php
endif;


if ( function_exists('the_subscribe_form') ) :
?>	<li>
		<div class="widget">
		<?php the_subscribe_form(); ?>		</div>
	</li>
<?php
endif;


if ( function_exists('the_subscribe_links') ) :
?>	<li>
		<div class="widget">
		<?php the_subscribe_links(); ?>		</div>
	</li>
<?php
endif;


if ( function_exists('the_recent_posts') ) :
?>	<li>
		<div class="widget">
		<?php the_recent_posts(); ?>		</div>
	</li>
<?php
endif;


if ( function_exists('the_recent_updates') ) :
?>	<li>
		<div class="widget">
		<?php the_recent_updates(); ?>		</div>
	</li>
<?php
endif;


if ( function_exists('the_recent_comments') ) :
?>	<li>
		<div class="widget">
		<?php the_recent_comments(); ?>		</div>
	</li>
<?php
endif;


if ( !get_nav_menu('sidebar_nav') ) :
?>	<li>
		<div class="widget">
		<h2><?php echo __('Pages'); ?></h2>
		<ul>
		<?php wp_list_pages('sort_column=menu_order&title_li='); ?>		</ul>
		</div>
	</li>
<?php
endif;


?>	<li>
		<div class="widget widget_categories">
		<h2><?php echo __('Categories'); ?></h2>
		<ul>
		<?php wp_list_categories('title_li=&sort_column=name&optioncount=0'); ?>		</ul>
		</div>
	</li>
<?php


?>	<li>
		<div class="widget widget_archives">
		<h2><?php echo __('Archives'); ?></h2>
		<ul>
		<?php wp_get_archives('type=monthly&show_post_count=0'); ?>		</ul>
		</div>
	</li>
<?php

	wp_meta();
} # end no widgets
?></ul>
</div>
</div><!-- #ext_sidebar -->