<?php
#
# DO NOT EDIT THIS FILE
# ---------------------
# The Semiologic theme features a custom.php feature. This allows to hook into
# the template without editing its php files. That way, you won't need to worry
# about losing your changes when you upgrade your site.
#
# You'll find detailed sample files in the custom-samples folder
#


#
# initialize
#

$GLOBALS['semiologic'] = get_settings('semiologic');

#echo '<pre>';
#var_dump($GLOBALS['semiologic']);
#echo '</pre>';

if ( !$GLOBALS['semiologic'] )
{
	include_once ABSPATH . 'wp-admin/admin-functions.php';
	include_once dirname(__FILE__) . '/utils/wizards.php';
	include_once dirname(__FILE__) . '/admin/skin.php';

	include_once dirname(__FILE__) . '/wizards/autoinstall/autoinstall.php';

	install_semiologic();
}


#
# true() and false()
# these are useful to override theme defaults in the custom.php file
# e.g. add_filter('show_entry_date', 'false');
#

if ( !function_exists('true') )
{
	function true($bool = null)
	{
		return true;
	} # end true()
}

if ( !function_exists('false') )
{
	function false($bool = null)
	{
		return false;
	} # end false()
}


#
# reset_plugin_hook()
#

function reset_plugin_hook($plugin_hook = null)
{
	if ( isset($plugin_hook) )
	{
		foreach ( (array) $GLOBALS['wp_filter'][$plugin_hook] as $priority => $plugins )
		{
			foreach ( (array) $plugins as $plugin )
			{
				remove_filter($plugin_hook, $plugin['function'], $priority, $plugin['accepted_args']);
			}
		}
	}
} # end reset_plugin_hook()


#
# include utils
#

foreach ( (array) glob(dirname(__FILE__) . '/utils/*.php') as $inc_file )
{
	include_once $inc_file;
}
foreach ( (array) glob(ABSPATH . 'wp-content/plugins/semiologic/utils/*.php') as $inc_file )
{
	include_once $inc_file;
}


#
# include admin screens
#

if ( strpos($_SERVER['REQUEST_URI'], 'wp-admin') !== false )
{
	foreach ( (array) glob(dirname(__FILE__) . '/admin/*.php') as $inc_file )
	{
		include_once $inc_file;
	}
	foreach ( (array) glob(ABSPATH . 'wp-content/plugins/semiologic/admin/*.php') as $inc_file )
	{
		include_once $inc_file;
	}
}


#
# include custom.php and skin.php files
#

$inc_file = TEMPLATEPATH . '/custom.php';

if ( file_exists($inc_file) )
{
	include_once $inc_file;
}

$inc_file = TEMPLATEPATH . '/skins/' . get_active_skin() . '/skin.php';

if ( file_exists($inc_file) )
{
	include_once $inc_file;
}

$inc_file = TEMPLATEPATH . '/skins/' . get_active_skin() . '/custom.php';

if ( file_exists($inc_file) )
{
	include_once $inc_file;
}


#
# register sidebars widgets
#

if ( function_exists('register_sidebars') )
{
	register_sidebars(strlen($GLOBALS['semiologic']['active_layout']) - 1);
}

/*
reset_plugin_hook('display_header');
reset_plugin_hook('display_navbar');
reset_plugin_hook('display_footer');
reset_plugin_hook('display_entry_header');
reset_plugin_hook('display_entry_title_meta');
reset_plugin_hook('display_entry_body');
reset_plugin_hook('display_entry_meta');
reset_plugin_hook('display_entry_actions');
reset_plugin_hook('before_the_wrapper');
reset_plugin_hook('before_the_entries');
reset_plugin_hook('before_the_entry');
reset_plugin_hook('after_the_entry');
reset_plugin_hook('after_the_entries');
reset_plugin_hook('after_the_wrapper');
reset_plugin_hook('template_redirect');
*/
?>