<?php
#
# DO NOT EDIT THIS FILE
# ---------------------
# The Semiologic theme features a custom.php feature. This allows to hook into
# the template without editing its php files. That way, you won't need to worry
# about losing your changes when you upgrade your site.
#
# You'll find detailed sample files in the custom-samples folder
#


# show header
include_once TEMPLATEPATH . '/header.php';

do_action('before_the_entries');

# show posts
if ( have_posts() )
{
	while ( have_posts() )
	{
		the_post();

?>
<div class="entry" id="entry-<?php the_ID(); ?>">
<?php
		do_action('before_the_entry');
		do_action('display_entry_header');
		do_action('display_entry_body');
		do_action('display_entry_spacer');
		do_action('display_entry_meta');
		do_action('display_entry_actions');
		do_action('after_the_entry');
		comments_template();
?>
</div>
<?php
	}

}
# or fallback
else
{
	do_action('display_404');
}

if ( !is_single() && !is_page() )
{
	posts_nav_link(' &bull; ', '&laquo;&nbsp;' . get_caption('previous_page'), get_caption('next_page') . '&nbsp;&raquo;');
}

do_action('after_the_entries');

# show footer
include_once TEMPLATEPATH . '/footer.php';
?>