<?php
#
# DO NOT EDIT THIS FILE
# ---------------------
# The Semiologic theme features a custom.php feature. This allows to hook into
# the template without editing its php files. That way, you won't need to worry
# about loosing your changes when you upgrade your site.
#
# You'll find detailed sample files in the skins directory
#



if ( apply_filters('show_entry_comments', true) ) :


if ( $post->post_password !== ''
	&& $_COOKIE['wp-postpass_' . COOKIEHASH] != $post->post_password
	)
{
	echo '<p>'
		. __('Enter your password to view comments.')
		. '</p>';

	return;
}


#
# Display comments
#

if ( $comments )
{
	$login_url = trailingslashit(get_option('siteurl')) . 'wp-login.php?redirect_to=' . urlencode(get_permalink());
?>
<div id="comments" class="comments">
<h1><?php comments_number(__('No Comments'), __('1 Comment'), __('% Comments')); ?>
<?php
	if ( comments_open() )
	{
?>
	<span class="comment_entry"><a href="#postcomment" title="<?php echo __('Leave a comment'); ?> ">&raquo;</a></span>
<?php
	}
?>
</h1>
<?php

	foreach ( $comments as $comment )
	{
		if ( function_exists('wp_gravatar') )
		{
			if ( in_array(get_comment_type(), array("pingback", "trackback")) )
			{
				$gravatar_url = wp_gravatar($comment->comment_author_url);
			}
			else
			{
				$gravatar_url = wp_gravatar($comment->comment_author_email);
			}
		}
		else
		{
			$gravatar_url = false;
		}
?>
<div id="comment-<?php comment_ID() ?>" class="comment">
<div class="comment_header">
	<h2><?php comment_date() ?></h2>
	<h3><?php
			echo ( $gravatar_url
				? '<img src="' . $gravatar_url . '" class="gravatar" alt="" />'
				: ''
				);
		?>
		<span class="comment_author"><?php comment_author_link(); ?></span> <?php comment_type(__('said:'), __('(Trackback)'), __('(Pingback)')); ?></h3>
</div>
<div class="comment_body">
<?php comment_text() ?>
</div>
<div class="spacer"></div>
<div class="comment_actions">
	<span class="action link_comment"><a href="#comment-<?php comment_ID() ?>"><?php echo __('Permalink') ?></a></span>
	<?php
	if ( comments_open() )
	{
	?>
	<span class="action reply_comment">&bull;&nbsp;<a href="#postcomment"><?php echo __('Reply'); ?></a></span>
	<?php
	}

	edit_comment_link(__('Edit'), ' <span class="action admin_link edit_comment">&bull;&nbsp;', '</span>'); ?>
</div>
</div> <!-- #comment -->
<?php
	} # foreach $comments as $comment
?>
</div><!-- #comments -->
<?php
} # if $comments


#
# Display comment form
#

if ( comments_open() && !( isset($_GET['action']) && $_GET['action'] == 'print' ) )
{
?>
<div id="comment_form" class="comment_form">
<h1 id="postcomment"><?php _e('Leave a comment'); ?></h1>

<?php if ( get_option('comment_registration') && !$user_ID )
{
?>
<p><?php echo str_replace('%login_url%', $login_url, __('You must be <a href="%login_url%">logged in</a> to post a comment.')); ?></p>
<?php
}
else
{
?>
<form action="<?php echo get_option('siteurl'); ?>/wp-comments-post.php" method="post" id="commentform">
<?php
if ( $user_ID )
{
?>
<p>Logged in as <span class="comment_author"><a href="<?php echo trailingslashit(get_option('siteurl')); ?>wp-admin/profile.php"><?php echo $user_identity; ?></a></span>. <span class="loginout"><a href="<?php echo trailingslashit(get_option('siteurl')); ?>wp-login.php?action=logout" title="<?php echo __('Log out of this account') ?>">Logout &raquo;</a></span></p>
<?php
}
else
{
?>
<p><label for="author"><?php echo __('Name'); if ($req) echo ' ' . __('(required)'); ?>:</label><br />
<input type="text" name="author" id="author" value="<?php echo $comment_author; ?>" /></p>

<p><label for="email"><?php echo __('Email');  if ($req) echo ' ' . __('(required)'); ?>:</label><br />
<input type="text" name="email" id="email" value="<?php echo $comment_author_email; ?>" /></p>

<p><label for="url"><?php echo __('Web site'); ?>:</label><br />
<input type="text" name="url" id="url" value="<?php echo $comment_author_url; ?>" /></p>

<?php
} # if ( $user_ID )

?>

<p><textarea name="comment" id="comment" cols="48" rows="10" tabindex="4"></textarea></p>

<p><input name="submit" type="submit" id="submit" tabindex="5" value="<?php echo __('Submit Comment'); ?>" />
<input type="hidden" name="comment_post_ID" value="<?php echo $id; ?>" />
</p>
<?php
do_action('comment_form', $post->ID);
?>
</form>
<?php
} # get_option('comment_registration') && !$user_ID
?>
</div><!-- #commentform -->
<?php
} # comments_open()

endif;
?>