<?php
#
# Do not edit this file if you don't understand it
#

$GLOBALS['semiologic'] = array(
	'nav_menus' => array(
		'header_nav' => array(
			'Home' => get_bloginfo('home'),
			'Blog' => 'blog',
			'About' => 'about',
			'Contact' => 'contact'
			),
		'sidebar_nav' => array(
			),
		'footer_nav' => array(
			'Archives' => 'archives',
			'About' => 'about',
			'Contact' => 'contact'
			)
		),
	'active_skin' => array(
		'skin' => 'sky-gold',
		'name' => 'Sky Gold',
		'author' => 'Denis de Bernardy',
		'author_uri' => 'http://www.mesoconcepts.com'
		),
	'active_layout' => 'mse',
	'active_width' => 'wide',
	'active_header' => '',
	'active_font' => 'bookman',
	'captions' => array(
			'search' => __('Search'),
			'go' => __('Go'),
			'copyright' => __('Copyright %year%, %admin_name%'),
			'edit' => __('Edit'),
			'by' => __('By'),
			'more' => __('More'),
			'page' => __('Page'),
			'filed_under' => __('Filed under'),
			'permalink' => __('Permalink'),
			'print' => __('Print'),
			'email' => __('Email'),
			'comment' => __('Comment'),
			'no_comments' => __('No Comments'),
			'1_comment' => __('1 Comment'),
			'n_comments' => __('% Comments'),
			'trackback_uri' => __('Trackback uri'),
			'track_this_entry' => __('Track this entry'),
			'related_entries' => __('Related Entries'),
			'no_entries_found' => __('No entries found'),
			'previous_page' => __('Previous Page'),
			'next_page' => __('Next Page')
		)
	);


#
# pro package auto installer
# (saves *lots* of time)
#

if ( file_exists(ABSPATH . 'wp-content/plugins/semiologic/defaults.php') )
{
	include_once ABSPATH . 'wp-content/plugins/semiologic/defaults.php';
}

#
# save options
#

update_option('semiologic', $GLOBALS['semiologic']);


#
# regenerate nav menu
#

include_once TEMPLATEPATH . '/admin/nav-menus.php';
regen_theme_nav_menu_cache();
?>