<?php
#
# DO NOT EDIT THIS FILE
# ---------------------
# The Semiologic theme features a custom.php feature. This allows to hook into
# the template without editing its php files. That way, you won't need to worry
# about loosing your changes when you upgrade your site.
#
# You'll find detailed sample files in the skins directory
#
?>
</div>
</div><!-- #main -->

<?php
do_action('display_sidebar');
do_action('display_body_spacer');
?>

</div><!-- #body -->

<?php
do_action('before_the_footer');
do_action('display_footer');
do_action('after_the_footer');
?>

</div><!-- #wrapper -->

<?php
do_action('display_ext_sidebar');
do_action('display_canvas_spacer');
?>

</div><!-- #shadow -->
<div id="shadow_bottom"></div>
</div><!-- #ext_wrapper -->
<?php
do_action('after_the_wrapper');
do_action('wp_footer');
?>
</body>
</html>