<?php
#
# DO NOT EDIT THIS FILE
# ---------------------
# The Semiologic theme features a custom.php feature. This allows to hook into
# the template without editing its php files. That way, you won't need to worry
# about loosing your changes when you upgrade your site.
#
# You'll find detailed sample files in the skins directory
#


#
# initialize
#

$GLOBALS['semiologic'] = get_settings('semiologic');

if ( !$GLOBALS['semiologic'] )
{
	include_once dirname(__FILE__) . '/defaults.php';
}


#
# register sidebars widgets
#

if ( function_exists('register_sidebars') )
{
	register_sidebars(2);
}


#
# true() and false()
# these are useful to override theme defaults in the custom.php file
# e.g. add_filter('show_entry_date', 'false');
#

if ( !function_exists('true') )
{
	function true($bool = null)
	{
		return true;
	} # end true()
}

if ( !function_exists('false') )
{
	function false($bool = null)
	{
		return false;
	} # end false()
}


#
# reset_plugin_hook()
#

function reset_plugin_hook($plugin_hook = null)
{
	if ( isset($plugin_hook) )
	{
		foreach ( (array) $GLOBALS['wp_filter'][$plugin_hook] as $priority => $plugins )
		{
			foreach ( (array) $plugins as $plugin )
			{
				remove_filter($plugin_hook, $plugin['function'], $priority, $plugin['accepted_args']);
			}
		}
	}
} # end reset_plugin_hook()


#
# include utils
#

foreach ( (array) glob(dirname(__FILE__) . '/utils/*.php') as $inc_file )
{
	include_once $inc_file;
}
foreach ( (array) glob(ABSPATH . 'wp-content/plugins/semiologic/utils/*.php') as $inc_file )
{
	include_once $inc_file;
}


#
# include admin screens
#

if ( strpos($_SERVER['REQUEST_URI'], 'wp-admin') !== false )
{
	foreach ( (array) glob(dirname(__FILE__) . '/admin/*.php') as $inc_file )
	{
		include_once $inc_file;
	}
	foreach ( (array) glob(ABSPATH . 'wp-content/plugins/semiologic/admin/*.php') as $inc_file )
	{
		include_once $inc_file;
	}
}


#
# include custom.php
#

$inc_file = TEMPLATEPATH . '/skins/' . get_active_skin() . '/custom.php';

if ( file_exists($inc_file) )
{
	include_once $inc_file;
}
else
{
	$inc_file = TEMPLATEPATH . '/custom.php';

	if ( file_exists($inc_file) )
	{
		include_once $inc_file;
	}
}
?>