<?php
#
# DO NOT EDIT THIS FILE
# ---------------------
# The Semiologic theme features a custom.php feature. This allows to hook into
# the template without editing its php files. That way, you won't need to worry
# about loosing your changes when you upgrade your site.
#
# You'll find detailed sample files in the skins directory
#
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html><head><title><?php do_action('display_page_title'); ?></title>
<?php
do_action('wp_head');
?>
</head>
<body class="<?php do_action('display_page_class'); ?>">
<?php
do_action('before_the_wrapper');
?>
<div id="ext_wrapper">
<div id="shadow_top"></div>
<div id="shadow">
<div id="wrapper">

<?php
do_action('before_the_header');
do_action('display_header');
do_action('display_navbar');
do_action('after_the_header');
?>

<div id="body" class="body">
<div id="main" class="main">
<div class="pad">