<?php
#
# DO NOT EDIT THIS FILE
# ---------------------
# The Semiologic theme features a custom.php feature. This allows to hook into
# the template without editing its php files. That way, you won't need to worry
# about loosing your changes when you upgrade your site.
#
# You'll find detailed sample files in the skins directory
#
?>

<div id="sidebar" class="sidebar">
<div class="pad">
<ul>
<?php
if ( function_exists('dynamic_sidebar') )
{
	if( in_array($GLOBALS['semiologic']['active_layout'], array('sme', 'mse', 'sm', 'ms')) )
	{
		dynamic_sidebar(1);
	}
	else
	{
		dynamic_sidebar(2);
	}
}
else  # no widgets
{

if ( function_exists('the_sidebar_tile') ) :
?>
	<li>
		<div class="widget">
		<?php the_sidebar_tile(); ?>
		</div>
	</li>
<?php
endif;


if ( function_exists('the_sidebar_ad') && $GLOBALS['sem_ad_space']->ad_distribution['sidebar'] ) :
?>
	<li>
		<div class="widget">
		<?php the_sidebar_ad(); ?>
		</div>
	</li>
<?php
endif;


if ( function_exists('jal_democracy') ) :
?>
	<li>
		<div class="widget">
		<h2>Poll</h2>
		<?php jal_democracy(); ?>
		</div>
	</li>
<?php
endif;


if ( function_exists('the_recent_links') ) :
?>
	<li><?php the_recent_links(); ?></li>
<?php
endif;


global $wpdb;

$link_cats = $wpdb->get_results("
SELECT
	cat_id, cat_name, COUNT( link_id ) as num_links
FROM
	$wpdb->linkcategories
INNER JOIN
	$wpdb->links ON link_category = cat_id
WHERE
	link_visible = 'Y'
GROUP BY
	cat_id
HAVING
	num_links > 0
ORDER BY
	cat_name
");

if ( $link_cats ) :
	foreach ( $link_cats as $link_cat )
	{
?>
	<li>
		<div class="widget">
		<h2><?php echo stripslashes($link_cat->cat_name); ?></h2>
		<ul>
		<?php wp_get_links($link_cat->cat_id); ?>
		</ul>
	</li>
<?php
	}
endif;

} # end no widgets
?>
</ul>
</div>
</div><!-- #sidebar -->