<?php
#
# DO NOT EDIT THIS FILE
# ---------------------
# The Semiologic theme features a custom.php feature. This allows to hook into
# the template without editing its php files. That way, you won't need to worry
# about losing your changes when you upgrade your site.
#
# You'll find detailed sample files in the custom-samples folder
#

define('FALBUM', true);
define('FALBUM_STANDALONE', true);
require_once(ABSPATH . 'wp-blog-header.php');
require_once(ABSPATH . 'wp-content/plugins/falbum/falbum.php');

# force page type
$GLOBALS['wp_query']->is_page = true;

# show header
include_once TEMPLATEPATH . '/header.php';

do_action('before_the_entries');
do_action('before_the_entry');

# show flickr
?>
<script type="text/javascript" src="<?php echo trailingslashit(get_settings('siteurl')); ?>wp-content/plugins/falbum/falbum.js"></script>
<script type="text/javascript" src="<?php echo trailingslashit(get_settings('siteurl')); ?>wp-content/plugins/falbum/overlib.js"></script>
<script type="text/javascript" src="<?php echo trailingslashit(get_settings('siteurl')); ?>wp-content/plugins/falbum/res/prototype.js"></script>

<div id="overDiv" style="position:absolute; visibility:hidden; z-index:1000;" class="entry"></div>
<div class="narrowcolumn">
<?php
	$falbum->show_photos();
?></div>
<div class="spacer"></div>
<?php

do_action('after_the_entry');
do_action('after_the_entries');

# show footer
include_once TEMPLATEPATH . '/footer.php';
?>